### PR TITLE
Resolve code block copy issue #296

### LINKED ISSUE #296: Install step copy feature on documentation is possibly incorrect
Documentation link: https://docs.openzeppelin.com/contracts/4.x/#install

When I press the copy icon this is saved to my machine `$ npm install @openzeppelin/contracts`. This throws an error on the terminal of `Expected a variable name after this $.` 

Because the copy command includes the `$` symbol. Is that expected or would it be better to only copy the executable part of the command `npm install @openzeppelin/contracts`? 

I'm willing to make this update if it is a bug.

### PR DESCRIPTION
**Pull request by TatisLois**
Fixes #296 

- Updates `ui/src/js/07-copy-code.js` to check if the code block lang a user is copying is `shell` or one of its aliases. 
- The check will conditionally strip out the leading `$` and empty space if it's a shell block that contains `$`

### CODE REVIEW

File: ui/src/js/07-copy-code.js [hunk 1]
```diff
@@ -8,7 +11,16 @@
   }
 
   function copyClick(e) {
-    const code = e.target.parentElement.innerText;
+    let code = e.target.parentElement.innerText;
+    const codeParentElement = e.target.parentElement;
+    const codeElement = codeParentElement.querySelector(codeElementSelector);
+    const codeLanguage = codeElement.dataset.lang;
+    const isShellLanguage = shellAliases.indexOf(codeLanguage) >= 0;
```
Comment (frangio) [inline ui/src/js/07-copy-code.js]:
```suggestion
    const isShellLanguage = shellAliases.includes(codeLanguage);
```

File: ui/src/js/07-copy-code.js [hunk 2]
```diff
@@ -8,7 +11,16 @@
...
+
+    if (isShellLanguage) {
+      const [firstChar] = code;
+      code = firstChar === '$' ? code.substring(2) : code;
```
Comment (frangio) [inline ui/src/js/07-copy-code.js]: This should be more reliable:

```suggestion
      code = code.replace(/^\$ /gm, '');
```

It will also remove the dollar sign on each line

Note that it only removes a dollar sign followed by a space. Otherwise we could potentially be looking at a variable (`$CMD arg0 arg1`...?).

File: ui/src/js/07-copy-code.js [hunk 3]
```diff
@@ -8,7 +11,16 @@
   }
 
   function copyClick(e) {
-    const code = e.target.parentElement.innerText;
+    let code = e.target.parentElement.innerText;
+    const codeParentElement = e.target.parentElement;
+    const codeElement = codeParentElement.querySelector(codeElementSelector);
```
Comment (frangio) [inline ui/src/js/07-copy-code.js:16]: Consider that this could return `null`.

**Review by frangio — COMMENTED** [review]
Thank you @TatisLois! Some minor comments

File: ui/src/js/07-copy-code.js (hunk 1 above)
Comment (TatisLois) [reply ui/src/js/07-copy-code.js]: I originally used include but noticed it does not support [IE 11](https://caniuse.com/array-includes) and did not see a transpile step in your build process so I decided to use the wider supported indexOf. 

Not sure what browsers the documentation targets but **I'll make the updates**. But let me know if what I mentioned above will be an issue.

File: ui/src/js/07-copy-code.js (hunk 2 above)
Comment (TatisLois) [reply ui/src/js/07-copy-code.js]: Good call out. I think I noticed a few multi-line shell examples so this solution is better. Thank you, will update!

File: ui/src/js/07-copy-code.js (hunk 3 above)
Comment (TatisLois) [reply ui/src/js/07-copy-code.js:16]: 💯 great observation will account for it in my update!

File: ui/src/js/07-copy-code.js (hunk 1 above)
Comment (frangio) [reply ui/src/js/07-copy-code.js]: I'm comfortable with dropping IE 11 to be honest. Ideally we would support it through transpilation but I don't want it to affect the source code. The Rollup setup could easily be expanded for that, I assume possibly `@rollup/babel` + `@babel/preset-env`. If that's something you want to help with that'd be cool!

Comment (TatisLois) [reply ui/src/js/07-copy-code.js]: That would be a good follow-up PR. I'll give it a shot! 😄

Comment (TatisLois) [reply ui/src/js/07-copy-code.js]: I opened a follow up PR for babel + rollup -> https://github.com/OpenZeppelin/docs.openzeppelin.com/pull/298

**Review by frangio — APPROVED** [review]
Awesome thank you!
